version: '3.3'

services:
  app:
    build: .
    container_name: robot-sparebin
    volumes:
      - .:/app:cached
    ports:
      - "8080:8080" # Caso precise de porta para a aplicação web
      - "5900:5900" # Porta para VNC, se necessário
    environment:
      - DISPLAY=:99
      - PIPENV_IGNORE_VIRTUALENVS=1
      - PIPENV_VENV_IN_PROJECT=1
    working_dir: /app
    command: bash -c "rm -rf /tmp/.X99-lock && tail -f /dev/null"
    tty: true

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017" # Porta do MongoDB
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
